Repository stolostron/deploy, pull requests merged in 2020-09, with the labels that each got.

#145 fix for issue 5065
  clean-clusters.sh
Labels: lgtm

#147 Move installer test results file mount destination
  dev/start.sh
Labels: lgtm

#152 Default to composite bundle.
  start.sh
Labels: lgtm

#151 adjust types to fix acm 2.0 model
  demo/spoke/cluster-deployment.yaml
  demo/spoke/cluster.yaml
  demo/spoke/endpoint-config.yaml
  demo/spoke/imageset.yaml
  demo/spoke/install-config.yaml
  demo/spoke/klusterlet-addon-config.yaml
  demo/spoke/kustomization.yaml
  demo/spoke/machine-pool.yaml
  demo/spoke/managed-cluster.yaml
  demo/spoke/reset.sh
  demo/spoke/start.sh
Labels: enhancement, lgtm

#154 Readme update to base64 encoding to avoid line breaks
  README.md
Labels: bug, lgtm

#153 Poll MCH status for 2.1.X+ deploys
  README.md
  start.sh
Labels: lgtm

#155 [hotfix] replay COMPOSITE_BUNDLE default that was backed out in a previous merge
  start.sh
Labels: lgtm

#157 Observability
  addons/observability/README.md
  addons/observability/example-observability-cr.yaml
  addons/observability/kustomization.yaml
  addons/observability/namespace.yaml
  addons/observability/reset.sh
  addons/observability/start.sh
  addons/observability/thanos.yaml
Labels: lgtm

#159 Fix a typo in the ICSP
  README.md
Labels: lgtm
