Repository stolostron/deploy, pull requests merged in 2021-05, with the labels that each got.

#182 update cleanup-managedcluster script to add deletion of klusterlet crd
  hack/cleanup-managed-cluster.sh
Labels: approved, lgtm

#185 Update example-multiclusterhub-cr.yaml
  multiclusterhub/example-multiclusterhub-cr.yaml
Labels: approved

#186 Revert "Update example-multiclusterhub-cr.yaml"
  multiclusterhub/example-multiclusterhub-cr.yaml
Labels: approved

#187 Toggle the inclusion of MCH annotations based on US/DS for AI
  acm-operator/kustomization.yaml
  acm-operator/subscription.yaml
  multiclusterhub/example-multiclusterhub-cr.yaml
  snapshot.ver
  start.sh
Labels: approved, lgtm

#184 Add support to activate search
  README.md
  start.sh
Labels: lgtm
