Repository stolostron/deploy, pull requests merged in 2021-02, with the labels that each got.

#142 2.1 appliedmanifestwork cleanup
  hack/cleanup-managed-cluster.sh
Labels: lgtm

#175 add command to show RHACM version
  version.sh
Labels: lgtm

#176 fix downstream rc deployments
  start.sh
Labels: bug, lgtm

#177 Add an OWNERS file to appease/enable the OSCI Bot
  OWNERS
  acm-operator/kustomization.yaml
  acm-operator/subscription.yaml
  snapshot.ver
Labels: lgtm

#174 Adding in a step to remove the open-cluster-management namespace on uninstall
  uninstall.sh
Labels: approved, lgtm
